# FriendlyChat

use_frameworks!
platform :ios, '12.0'

pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI'
pod 'Firebase/Auth'

target 'FriendlyChatSwift' do
end
